#!/bin/bash


SINCE=$(date -d 'yesterday' -Ins --utc | sed 's/,.*//')

if [[ -z "$SEARCH" ]]; then
  echo "must set SEARCH"
  exit 1
fi

if [[ -z "$EXCLUDE" ]]; then
  echo "must set EXCLUDE"
  exit 1
fi

docker ps -a | grep "$SEARCH" | grep -v "$EXCLUDE" | awk '{ print $1 }' \
  | xargs -n 1 -r docker inspect -f '{{.ID}} {{.Created}}' \
  | awk '$2 <= "'"$SINCE"'" { print $1 }' \
  | xargs docker stop \
  | xargs docker rm
